# Per:
# https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

name: Publish clamfig to PyPI

on:
  release:
    types: [published, released]

jobs:
  build-n-publish:
    name: Publish clamfig to PyPI
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user

    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .

    - name: Publish clamfig distribution to Test PyPI
      if: "github.event.release.prerelease"
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.CLAMFIG_TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish clamfig distribution  to PyPI
      if: "!github.event.release.prerelease"
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.CLAMFIG_PYPI_API_TOKEN }}

